basic functionality
ProdEng-JavaFrenzy/restaurant pull request #2
Opened 2022-03-01 21:37 UTC by AnitaTudor

## Checklist

- [ ] use a descriptive title for the branch: **feature/branch-name** or **fix/branch-name**
- [ ] use a descriptive title for the PR: **Feature / Fix <*PR title*> [#issue-number]**
- [ ] state the goal of the PR
- [ ] test locally
- [ ] update the docs and dependencies
- [ ] add unit tests
- [ ] update the issue number at the end of the PR
- [ ] squash commits and rebase on top of `main` before pushing
- [ ] delete this checklist

## Description
This PR fixes a bug / implements a new feature

## Issue
Closes #**issue-number**

2022-03-01 21:59 UTC, vladpirlog requested changes

2022-03-01 21:59 UTC, vladpirlog commented on src/main/java/ro/unibuc/hello/exception/ReservationNotFoundException.java
> +        super("Reservation " + identifier+" does not seem to exist!");
nit: leave a blank after `RuntimeException` and `identifier` (e.g.: `identifier + " does..."`)

2022-03-01 21:59 UTC, vladpirlog commented on src/main/java/ro/unibuc/hello/repository/ReservationRepository.java
> +}
nit: too many empty lines

2022-03-01 21:59 UTC, vladpirlog commented on src/main/java/ro/unibuc/hello/HelloApplication.java
> +
nit: too many empty lines

2022-03-01 21:59 UTC, vladpirlog commented on src/main/java/ro/unibuc/hello/controller/ReservationController.java
> +    @GetMapping("/checkReservation/{identifier}")
nit: empty line between methods

2022-03-01 21:59 UTC, vladpirlog commented on src/main/java/ro/unibuc/hello/utils/GenerateIdentifier.java
> +                int index = random.nextInt(alphabet.length());
nit: the `for` statement is indented too much

2022-03-01 22:24 UTC, vladpirlog requested changes

2022-03-01 22:24 UTC, vladpirlog commented on src/main/java/com/javafrenzy/restaurant/controller/ReservationController.java
> +
is this used anywhere?

2022-03-01 22:50 UTC, AnitaTudor reviewed
changed files according to vlad feedback

2022-03-02 10:17 UTC, vladpirlog approved these changes

2022-03-02 10:19 UTC, merged